In [1]:
import pandas as pd 
import numpy as np

In [5]:
df = pd.read_csv('/Users/mac/Documents/Chat-Bot-Telegram/DataSet/Amazon/amazon_products.csv')
df.head(200)

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400
...,...,...,...,...,...,...,...,...,...,...,...
195,B079SDF8Y7,"Ultra Lite Softside Expandable Spinner, Turquo...",https://m.media-amazon.com/images/I/91Av3gU3+n...,https://www.amazon.com/dp/B079SDF8Y7,4.5,0,109.99,0.00,104,False,0
196,B08LDPFN1K,X-Bag Large Spinner with Frame - 25 Inch - Sui...,https://m.media-amazon.com/images/I/41cjRJ4jet...,https://www.amazon.com/dp/B08LDPFN1K,4.8,0,320.00,0.00,104,False,0
197,B086GQDWQ9,"Out of Bounds, Smokey Purple, 24-Inch Checked",https://m.media-amazon.com/images/I/81XWDsxpTj...,https://www.amazon.com/dp/B086GQDWQ9,4.3,0,99.99,0.00,104,False,0
198,B01H19W70I,Designer Luggage Collection - Expandable 24 In...,https://m.media-amazon.com/images/I/71Q+1ujHhU...,https://www.amazon.com/dp/B01H19W70I,4.4,0,159.99,0.00,104,False,0
199,B00J9YQKFW,Lite-Cube - Spinner,https://m.media-amazon.com/images/I/91Ea1vU0PN...,https://www.amazon.com/dp/B00J9YQKFW,4.3,0,508.55,0.00,104,False,0

In [3]:
df.fillna(' ' , inplace=True)

In [4]:
df.drop(columns=['imgUrl'])

,asin,title,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400
...,...,...,...,...,...,...,...,...,...,...
1426332,B00R3LIKCO,American Flag Patriotic USA Classic 5 Panel Me...,https://www.amazon.com/dp/B00R3LIKCO,4.2,0,14.95,0.00,112,False,0
1426333,B098BQ7ZQ3,Men's Baseball Cap - H2O-DRI Line Up Curved Br...,https://www.amazon.com/dp/B098BQ7ZQ3,4.4,0,33.99,0.00,112,False,0
1426334,B07X1MVNT1,[4 Pack] Adjustable Eyeglasses and Sunglasses ...,https://www.amazon.com/dp/B07X1MVNT1,3.6,0,8.54,0.00,112,False,0
1426335,B08XLBG8V9,Ax2002 Aviator Sunglasses,https://www.amazon.com/dp/B08XLBG8V9,4.5,0,54.36,57.39,112,False,0
1426336,B07GH67QC8,in Hoc Signo Vinces Knights Templar Masonic Em...,https://www.amazon.com/dp/B07GH67QC8,4.9,0,18.79,0.00,112,False,0

In [7]:
df['title'] = df['title'].astype(str).str.lower()
df['title']

0          sion softside expandable roller luggage, black...
1          luggage sets expandable pc+abs durable suitcas...
2          platinum elite softside expandable checked lug...
3          freeform hardside expandable with double spinn...
4          winfield 2 hardside expandable luggage with sp...
                                 ...
1426332    american flag patriotic usa classic 5 panel me...
1426333    men's baseball cap - h2o-dri line up curved br...
1426334    [4 pack] adjustable eyeglasses and sunglasses ...
1426335                            ax2002 aviator sunglasses
1426336    in hoc signo vinces knights templar masonic em...
Name: title, Length: 1426337, dtype: object